
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqhjxaturfnjholigypt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxaGp4YXR1cmZuamhvbGlneXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MjgwMTQsImV4cCI6MjA2NDIwNDAxNH0.sM9fVWBFjtRwfIpIfn6XJL2KwC6tR-e-1Bwgdu_eIZo";

// Configure Supabase client with proper auth settings
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
